apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-ip-webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostname-ip-webapp
  template:
    metadata:
      labels:
        app: hostname-ip-webapp
    spec:
      containers:
      - name: hostname-ip-webapp
        image: <your_docker_hub_username>/hostname-ip-webapp:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: hostname-ip-webapp-service
spec:
  selector:
    app: hostname-ip-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer